name: PBWT TEST

on: [push]


jobs:
  update:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install virtualenv pyinstaller pytest &&
          make install

      - name: Running c tests
        run: make test-c

      - name: Running python tests
        run: |
          export PYTHONPATH=PATHONPATH:./venv/lib/python3.8/site-packages/ &&
          make test-cli
